### ISSUE TITLE
Display individual wheel locking

### ISSUE THREAD

**Issue by hujkis** [cdemetriadis/lovely-dashboard#2]
It would be great to have a way to communicate to the driver that wheel(s) are locking under braking. Perhaps by a flashing individual wheel segment on the primary screen.  
This could be helpful for adjusting abs, bb settings.  

Thank You for your work!

**Comment by cdemetriadis** [comment]
Added to the To-do list. Thanks!

**Comment by cdemetriadis** [comment]
Hello @hujkis, not sure if you've seen this, but the latest version now includes Wheel Spin & Locking indication - ACC Only.

**Comment by hujkis** [comment]
You're a hero @cdemetriadis !  
Guess I'm ordering vocore screen...
