### ISSUE TITLE
Display Issue 

### ISSUE THREAD

**Issue by kingjaywong** [cdemetriadis/lovely-dashboard#7]
1.5 and 1.5.1 is not working on my computer. I followed the installation steps, only skipped step 3 which is Optional for iRacing. But it keep displaying almost nothing on my side. Here is the screenshot
![IMG_6987](https://user-images.githubusercontent.com/10363101/185599904-b0db0904-d1e2-4d7d-aa83-f8c769deb334.jpg)

BTW, 1.4 is working perfectly on my side. Could you please help to solve the issue ? Thank you so much.

SimBub version: 8.0.4

**Comment by cdemetriadis** [comment]
Hey there @kingjaywong, sorry for this. The dashboard is compatible with Assetto Corsa Competizione and iRacing only for now. Unfortunately, AC is not.

**Comment by kingjaywong** [comment]
Thank you very much for the reply, that explains a lot. Then I will keep both 1.4 and the latest version.
